source :rubygems

group :sinatra do
    gem "sinatra", '>=2.0'
    gem "thin"
end

group :misc do
    gem 'json'
	gem 'plist'
	gem 'to_xml'
end

group :test do 
	gem "rack-test"
	gem "rspec"
end

group :debug do
	gem 'byebug'
	gem 'pry'
end
