source :rubygems

group :sinatra do
    gem "sinatra", '~>1.0'
    gem "thin"
end

group :misc do
    gem 'json'
	gem 'plist'
end

group :test do 
	gem "rack-test", '~>0.5.3'
	gem "rspec"
	gem 'ruby-debug'
end
